### ISSUE TITLE
Comment Field Bug in CSV Export

### ISSUE THREAD

**Issue by anabotescu** [Regnology/lucy#15]
**Describe the bug**
When we export the full report from Lucy, the comment field is wrongly exported, mingled with libraries.

**To Reproduce**
1.Open a product
2. Go to "Reports"
3. Click on OSS List > Full > Download
4. See - the field "Compliance Comment" mingled with libraries.

**Expected behavior**
One solution may be to put the compliance comment into " "-> which is the usual text identification in CSV (for Excel).
It might make sense to put all text fields in ""
Downloaded CSV with large comments can be opened in Excel without breaking the format of the table.

![Lucy_2023](https://user-images.githubusercontent.com/124244116/216638067-1423fecf-f94c-4254-897a-7ec738fad37c.PNG)

**Comment by patrickwjh** [comment]
The problem is that for the "Full" export the Apache commons-csv library isn't used. I've adjusted the code and now the CSV creation is done with the commons-csv library which handles all different special characters automatically, like the delimiter or quotes in the comment fields.

I've opened a pull request #16.
